### ISSUE TITLE
v1.3.0

### ISSUE THREAD

**Issue by maxchang3** [maxchang3/hexo-markmap#58]
- [ ] 兼容 JSON options (#55)
  - [ ] 重构部分代码，使用 JSDoc (#57)
  - [ ] 升级 `markmap` 至最新版本 (#56, https://github.com/maxchang3/hexo-markmap/commit/37349f5f0699f550dca95dd196d9353c30bf5722)
    - [ ] 解决 KaTeX 字体渲染问题

**Comment by maxchang3** [comment]
[v2.0.0](https://github.com/markmap-universe/hexo-markmap/releases/tag/v2.0.0) 已经发布。
